# Data Handling Mini Project using NumPy and Pandas

## Project Overview

I am excited to work on this mini project as an opportunity to apply the concepts I have learned in NumPy and Pandas to a real-world data handling task.

Throughout this project, I will explore how data can be loaded, cleaned, transformed, analyzed, and visualized using Python's powerful data analysis libraries. This project will help strengthen my understanding of data structures, numerical computation, and data manipulation techniques that are essential in data science and artificial intelligence.

## Objectives

- Practice working with datasets using Pandas.
- Perform data cleaning and preprocessing.
- Use NumPy for efficient numerical operations.
- Generate meaningful insights from data.
- Improve problem-solving and analytical skills through hands-on implementation.

## Learning Goals

By completing this project, I aim to:

- Gain confidence in handling real datasets.
- Understand how NumPy and Pandas work together.
- Learn best practices for organizing data analysis workflows.
- Build a strong foundation for future machine learning and AI projects.

Let's begin the analysis.

# Global Countries Analysis

An exploratory data analysis of countries across continents, regions, governments, demographics, and political structures using Python and Pandas.

In [15]:
import numpy as np 
import pandas as pd

In [16]:
#Now lets read the file so we can extract its content
df = pd.read_csv(r"/kaggle/input/datasets/oorjaasonthalia/countries-csv/Countries.csv")

## Dataset Overview

Before conducting analysis, the dataset was inspected to understand its structure, data types, and overall quality.

The inspection included:

- Dataset dimensions
- Column information and data types
- Summary statistics
- Missing value identification
- Duplicate record detection

These checks help ensure that subsequent analyses are based on reliable and well-understood data.

In [17]:
#View dimensions of matrix
df.shape

(194, 64)

In [18]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [19]:
df.nunique()

country             194
country_long        194
currency            142
capital_city        194
region               22
                   ...
democracy_score     146
democracy_type        5
median_age          143
political_leader    187
title                17
Length: 64, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [21]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [22]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [23]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [24]:
df.isna().sum().sort_values(ascending=False)

internally_displaced_persons               121
central_government_debt_pct_gdp             74
hiv_incidence                               61
electricty_production_hydroelectric_pct     56
electricty_production_oil_pct               56
                                          ...
urban_population                             0
democracy_score                              0
press                                        0
median_age                                   0
democracy_type                               0
Length: 64, dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

# Population and Demographics

Population size, age structure, and fertility patterns provide important insights into demographic trends and future population growth.

This section explores population distribution, median age, and fertility patterns across countries and continents.

In [41]:
df.sort_values("population",ascending=False)[["country","population"]].head(10)

           country  population
75           India  1417173173
34           China  1412175000
184  United States   333287557
76       Indonesia   275501339
129       Pakistan   235824862
125        Nigeria   218541212
22          Brazil   215313498
12      Bangladesh   171186372
140         Russia   143555736
109         Mexico   127504125

In [78]:
df.sort_values("population")[["country","population"]].head(10)

                 country  population
179               Tuvalu       11312
119                Nauru       12668
130                Palau       18055
143           San Marino       33660
112               Monaco       36469
97         Liechtenstein       39327
106     Marshall Islands       41569
159  St. Kitts and Nevis       47657
48              Dominica       72737
3                Andorra       79824

In [43]:
df.groupby("continent")["population"].sum().sort_values(ascending=False)

continent
Asia        4678097293
Africa      1424810790
Americas    1027724027
Europe       738525508
Oceania       43884673
Name: population, dtype: int64

In [44]:
df.groupby("continent")["median_age"].mean().sort_values(ascending=False)

continent
Europe      37.900000
Americas    26.840000
Asia        25.555319
Oceania     21.500000
Africa      16.098148
Name: median_age, dtype: float64

In [47]:
df.sort_values("fertility_rate")[["country","fertility_rate"]].head(10)

        country  fertility_rate
88        Korea           0.808
130       Palau           0.850
150   Singapore           1.120
105       Malta           1.140
181     Ukraine           1.160
34        China           1.164
157       Spain           1.190
81        Italy           1.250
143  San Marino           1.260
3       Andorra           1.270

In [48]:
df.sort_values("fertility_rate")[["country","fertility_rate"]].tail(10)

                      country  fertility_rate
26                    Burundi           5.078
125                   Nigeria           5.237
4                      Angola           5.304
104                      Mali           5.956
31   Central African Republic           5.978
45            Dem. Rep. Congo           6.156
32                       Chad           6.255
154                   Somalia           6.312
124                     Niger           6.820
112                    Monaco             NaN

### Fertility Patterns

Fertility rates vary significantly across countries and regions.

Countries with high fertility rates typically experience faster population growth and younger age structures, while countries with low fertility rates often face aging populations and slower demographic expansion.

These differences can have major implications for workforce size, economic development, healthcare systems, and long-term population sustainability.

# Democracy and Governance

Political institutions play a major role in shaping national development.

This section explores how democratic systems vary across countries and continents, examining democracy scores, governance structures, and the distribution of political systems around the world.

In [49]:
df.sort_values("democracy_score")[["country","democracy_score"]].head(10)

                   country  democracy_score
148             Seychelles              0.0
144  São Tomé and Principe              0.0
130                  Palau              0.0
187                Vanuatu              0.0
179                 Tuvalu              0.0
16                  Belize              0.0
13                Barbados              0.0
23                  Brunei              0.0
103               Maldives              0.0
112                 Monaco              0.0

In [32]:
df.sort_values("democracy_score")[["country","democracy_score"]].tail(10)

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

### Global Democracy Rankings

Democracy scores provide a standardized measure of political freedoms, electoral processes, government functioning, and civil liberties.

Comparing the highest- and lowest-scoring countries helps identify major differences in governance quality across the world.

In [50]:
df.groupby("continent")[["democracy_score"]].mean()

           democracy_score
continent
Africa            3.971296
Americas          4.765429
Asia              4.120851
Europe            6.724773
Oceania           2.159286

### Continental Comparison

Democracy levels are not distributed evenly across continents.

By examining average democracy scores at the continental level, we can identify broader regional trends in governance and political development.

In [52]:
df.groupby("democracy_type")[["democracy_score"]].mean()

                  democracy_score
democracy_type
Authoritarian            2.829623
Flawed democracy         7.032642
Full democracy           8.852000
Hybrid regime            5.161538
Unknown                  0.000000

In [53]:
df["democracy_type"].value_counts()

democracy_type
Flawed democracy    53
Authoritarian       53
Hybrid regime       39
Unknown             29
Full democracy      20
Name: count, dtype: int64

### Distribution of Political Systems

Countries are classified into different democracy categories based on their political institutions and democratic performance.

Examining the frequency of each category provides insight into the global balance between stronger and weaker democratic systems.

## Democracy and Development

Democracy is often associated with improvements in education, healthcare, economic performance, and access to information.

To explore these relationships, average life expectancy, internet access, and GDP are compared across different democracy categories.

In [55]:
df.groupby("democracy_type")[["life_expectancy"]].mean().sort_values("life_expectancy", ascending=False)

                  life_expectancy
democracy_type
Full democracy          81.250000
Flawed democracy        73.320755
Unknown                 70.538462
Authoritarian           67.566038
Hybrid regime           67.564103

In [56]:
df.groupby("democracy_type")[["internet_pct"]].mean().sort_values("internet_pct", ascending=False)

                  internet_pct
democracy_type
Full democracy       92.375960
Flawed democracy     77.018651
Unknown              68.346536
Hybrid regime        54.404177
Authoritarian        51.590327

In [57]:
df.groupby("democracy_type")[["gdp"]].mean().sort_values("gdp", ascending=False)

                           gdp
democracy_type
Flawed democracy  9.759507e+11
Full democracy    8.762052e+11
Authoritarian     4.961138e+11
Hybrid regime     1.063564e+11
Unknown           3.459348e+09

### Observations

Comparing development indicators across democracy categories helps identify broader governance patterns.

While these results do not establish causation, they provide insight into whether more democratic systems tend to be associated with higher living standards, greater connectivity, and stronger economic performance.

Further analysis would be required to determine the strength and significance of these relationships.

# Health and Quality of Life

Health indicators provide insight into the well-being of populations and the effectiveness of national healthcare systems.

This section explores life expectancy, healthcare spending, and medical infrastructure across countries and continents.

In [58]:
df.sort_values("life_expectancy", ascending=False)[["country","life_expectancy"]].head(10)

           country  life_expectancy
165    Switzerland             84.0
88           Korea             84.0
83           Japan             84.0
97   Liechtenstein             84.0
30          Canada             83.0
74         Iceland             83.0
99      Luxembourg             83.0
105          Malta             83.0
157          Spain             83.0
8        Australia             83.0

In [59]:
df.sort_values("life_expectancy")[["country","life_expectancy"]].head(10)

                      country  life_expectancy
94                    Lesotho             53.0
125                   Nigeria             53.0
32                       Chad             53.0
31   Central African Republic             54.0
156               South Sudan             55.0
154                   Somalia             55.0
56                   Eswatini             57.0
39              Côte d'Ivoire             59.0
45            Dem. Rep. Congo             59.0
68                     Guinea             59.0

In [60]:
df.groupby("continent")[["life_expectancy"]].mean().sort_values("life_expectancy", ascending=False)

           life_expectancy
continent
Europe           78.170732
Asia             73.212766
Americas         72.571429
Oceania          70.142857
Africa           62.833333

### Life Expectancy Analysis

Life expectancy is one of the most widely used measures of overall development and public health.

Countries with high life expectancy often benefit from stronger healthcare systems, better living conditions, and improved access to education and nutrition.

In [61]:
df.groupby("continent")[["hospital_beds"]].mean().sort_values("hospital_beds", ascending=False)

           hospital_beds
continent
Europe          5.083256
Asia            3.158298
Oceania         3.021014
Americas        2.156000
Africa          1.348868

In [62]:
df.groupby("continent")[["health_expenditure_pct_gdp"]].mean().sort_values("health_expenditure_pct_gdp", ascending=False)

           health_expenditure_pct_gdp
continent
Oceania                      9.579200
Europe                       8.923753
Americas                     7.784384
Asia                         5.941783
Africa                       5.394523

### Continental Health Comparison

Comparing life expectancy across continents highlights regional differences in health outcomes and development levels.

These differences may be influenced by economic conditions, healthcare accessibility, education levels, and political stability.

# Economic Analysis

Economic indicators provide valuable insight into national prosperity, labor market conditions, and fiscal capacity.

This section examines GDP, inflation, unemployment, and tax revenue patterns across countries and continents.

### Key Areas Explored

- Countries with the highest and lowest GDP
- Inflation extremes across the world
- Continental differences in unemployment rates
- Tax revenue patterns by continent

Together, these indicators provide a broader picture of global economic development and stability.

In [64]:
# Top 10 countries by GDP
df.sort_values("gdp", ascending=False)[["country","gdp"]].head(10)

            country           gdp
184   United States  2.546270e+13
34            China  1.796320e+13
83            Japan  4.231140e+12
63          Germany  4.072190e+12
75            India  3.385090e+12
183  United Kingdom  3.070670e+12
60           France  2.782910e+12
140          Russia  2.240420e+12
30           Canada  2.139840e+12
81            Italy  2.010430e+12

In [65]:
# Bottom 10 countries by GDP
df.sort_values("gdp")[["country","gdp"]].head(10)

                   country          gdp
179                 Tuvalu   60349400.0
119                  Nauru  150922000.0
130                  Palau  217800000.0
87                Kiribati  223353000.0
106       Marshall Islands  279668000.0
110             Micronesia  427094000.0
174                  Tonga  469228000.0
144  São Tomé and Principe  546680000.0
48                Dominica  612048000.0
142                  Samoa  832422000.0

In [66]:
# Average GDP by continent
df.groupby("continent")[["gdp"]].mean().sort_values("gdp", ascending=False)

                    gdp
continent
Americas   9.675583e+11
Asia       7.989775e+11
Europe     5.400586e+11
Oceania    1.402479e+11
Africa     5.466804e+10

In [67]:
# Top 10 highest inflation countries
df.sort_values("inflation", ascending=False)[["country","inflation"]].head(10)

                  country  inflation
188             Venezuela   254.9490
93                Lebanon   154.7560
162                 Sudan   138.8080
193              Zimbabwe   104.7050
177                Turkey    72.3088
163              Suriname    52.4460
158             Sri Lanka    49.7211
77                   Iran    43.3890
166  Syrian Arab Republic    36.7023
71                  Haiti    33.9839

In [68]:
# Top 10 lowest inflation countries
df.sort_values("inflation")[["country","inflation"]].head(10)

                country  inflation
156         South Sudan  -6.687320
36              Comoros  -4.294870
87             Kiribati  -1.813080
48             Dominica  -0.727116
119               Nauru  -0.124751
179              Tuvalu   0.500581
172         Timor-Leste   0.958813
143          San Marino   1.045980
66              Grenada   1.219510
190  West Bank and Gaza   1.237480

In [69]:
# Average unemployment by continent
df.groupby("continent")[["unemployment_pct"]].mean().sort_values("unemployment_pct", ascending=False)

           unemployment_pct
continent
Africa             9.593151
Americas           7.633258
Asia               6.414809
Europe             6.380150
Oceania            3.869625

In [70]:
# Average tax revenue percentage by continent
df.groupby("continent")[["tax_revenue_pct_gdp"]].mean().sort_values("tax_revenue_pct_gdp", ascending=False)

           tax_revenue_pct_gdp
continent
Europe               23.865050
Oceania              21.115759
Americas             16.243294
Africa               14.339436
Asia                 12.009671

# Energy and Environment

Energy production and environmental indicators reveal how countries balance economic growth, energy demand, and environmental sustainability.

This section explores renewable energy usage, fossil fuel dependence, and greenhouse gas emissions across countries and continents.

In [72]:
# Top 10 renewable energy consumers
df.sort_values("renewable_energy_consumption_pct", ascending=False)[["country","renewable_energy_consumption_pct"]].head(10)

                      country  renewable_energy_consumption_pct
45            Dem. Rep. Congo                             96.16
154                   Somalia                             95.37
180                    Uganda                             93.03
95                    Liberia                             92.94
31   Central African Republic                             90.45
61                      Gabon                             90.12
57                   Ethiopia                             89.52
18                     Bhutan                             87.45
69              Guinea-Bissau                             87.26
193                  Zimbabwe                             84.36

In [73]:
# Top 10 fossil fuel consumers
df.sort_values("fossil_energy_consumption_pct", ascending=False)[["country","fossil_energy_consumption_pct"]].head(10)

                 country  fossil_energy_consumption_pct
23                Brunei                        99.9952
138                Qatar                        99.9950
2                Algeria                        99.9779
128                 Oman                        99.9632
145         Saudi Arabia                        99.9280
175  Trinidad and Tobago                        99.9195
11               Bahrain                        99.3658
85            Kazakhstan                        99.1739
96                 Libya                        99.1113
77                  Iran                        99.0226

In [74]:
# Average renewable energy consumption by continent
df.groupby("continent")[["renewable_energy_consumption_pct"]].mean().sort_values("renewable_energy_consumption_pct", ascending=False)

           renewable_energy_consumption_pct
continent
Africa                            56.441296
Europe                            27.172381
Americas                          24.679429
Oceania                           21.482857
Asia                              17.418298

In [75]:
# Average fossil fuel consumption by continent
df.groupby("continent")[["fossil_energy_consumption_pct"]].mean().sort_values("fossil_energy_consumption_pct", ascending=False)

           fossil_energy_consumption_pct
continent
Asia                           75.478258
Europe                         69.720200
Americas                       49.284209
Africa                         34.761081
Oceania                        14.937480

In [76]:
# Top 10 CO2 emitters
df.sort_values("co2_emissions", ascending=False)[["country","co2_emissions"]].head(10)

           country  co2_emissions
34           China     10944700.0
184  United States      4320530.0
75           India      2200840.0
140         Russia      1618270.0
83           Japan      1014060.0
77            Iran       616561.0
63         Germany       603350.0
88           Korea       569682.0
76       Indonesia       563197.0
30          Canada       516874.0

In [77]:
# Average CO2 emissions by continent
df.groupby("continent")[["co2_emissions"]].mean().sort_values("co2_emissions", ascending=False)

           co2_emissions
continent
Asia       425609.575435
Americas   179299.540857
Europe     113693.609524
Oceania     29859.014286
Africa      23594.271407

# Key Findings

## Demographics
- Population is highly concentrated among a small number of countries.
- Fertility rates vary significantly across regions.

## Governance
- Democracy scores differ considerably across continents.
- Certain democracy types are substantially more common than others.

## Health
- Life expectancy shows clear regional variation.
- Healthcare expenditure differs significantly across continents.

## Economy
- GDP is heavily concentrated among a small number of economies.
- Inflation and unemployment vary widely across countries.

## Energy & Environment
- Renewable energy adoption differs substantially across regions.
- Major CO₂ emissions are concentrated among a limited number of countries.